#ifndef PAD_H
#define PAD_H

#include "common.h"

union digital_pad_switches
{
    struct
    {
        u16 select : 1;
        u16 l3 : 1;
        u16 r3 : 1;
        u16 start : 1;
        u16 joypad_up : 1;
        u16 joypad_right : 1;
        u16 joypad_down : 1;
        u16 joypad_left : 1;
        u16 l2 : 1;
        u16 r2 : 1;
        u16 l1 : 1;
        u16 r1 : 1;
        u16 triangle : 1;
        u16 circle : 1;
        u16 cross : 1;
        u16 square : 1;
    };
    u16 value;
};

enum sio_state
{
    SIO_STATE_NONE = 0,
    SIO_STATE_READ_CONTROLLER,
    SIO_STATE_READ_MEMCARD
};

enum input_device_type
{
    INPUT_DEVICE_DIGITAL_PAD,
    INPUT_DEVICE_ANALOG_PAD,
    INPUT_DEVICE_MULTITAP
};

typedef union
{
    struct
    {
        u32 tx_started : 1;
        u32 rx_fifo_not_empty : 1;
        u32 tx_finished : 1;
        u32 rx_parity_error : 1;
        u32 : 3;
        u32 ack_is_low : 1;
        u32 : 1;
        u32 irq : 1;
        u32 : 1;
        u32 timer : 21; 
    };
    u32 value;
} SIO_STAT;

struct input_device_base
{
    enum input_device_type type;
    u16 (*input_get_data)(struct input_device_base *device);
    u8 data[6]; /* maximum number of input bytes generated by a device */
    //enum sio_state state;
    //u32 sequence_at; /* index in the communication sequence */
};

struct digital_pad
{
    struct input_device_base base;
    union digital_pad_switches buttons;
};

struct sio_context
{
    //union digital_pad_switches buttons;
    //u32 command_index;
    u32 sequence_len;
    enum sio_state state;
    struct input_device_base *devices[2];

    SIO_STAT stat;
    u16 mode;
    u16 control; 
    u16 baud_reload; // not sure if this needs a default value
    u8 bytes_left_until_irq;
    u8 tx_buffer; // TODO: remove
    u8 tx_buffer_full;
    u8 rx_buffer;
    u8 rx_has_data; /* debugging */
    u8 rx_buffer_full;
    u64 cycles_at_baud_store;
};

extern struct sio_context g_sio;

u16 sio_read(u32 offset);
void sio_store(u32 offset, u16 value);


#endif /* PAD_H */
