#ifndef PAD_H
#define PAD_H

#include "common.h"

#define MEMCARD_SIZE KILOBYTES(128)

enum digital_pad_button
{
    PAD_SELECT   = (1 << 0),
    PAD_L3       = (1 << 1),
    PAD_R3       = (1 << 2),
    PAD_START    = (1 << 3),
    PAD_UP       = (1 << 4),
    PAD_RIGHT    = (1 << 5),
    PAD_DOWN     = (1 << 6),
    PAD_LEFT     = (1 << 7),
    PAD_L2       = (1 << 8),
    PAD_R2       = (1 << 9),
    PAD_L1       = (1 << 10),
    PAD_R1       = (1 << 11),
    PAD_TRIANGLE = (1 << 12),
    PAD_CIRCLE   = (1 << 13),
    PAD_CROSS    = (1 << 14),
    PAD_SQUARE   = (1 << 15)
};

enum sio_state
{
    SIO_STATE_NONE = 0,
    SIO_STATE_READ_CONTROLLER,
    SIO_STATE_READ_MEMCARD
};

enum mcd_command
{
    MCD_COMMAND_READ,
    MCD_COMMAND_WRITE,
    MCD_COMMAND_ID
};

typedef enum input_device_type
{
    INPUT_DEVICE_DIGITAL_PAD,
    INPUT_DEVICE_ANALOG_PAD
} input_device_type;

typedef union
{
    struct
    {
        u32 tx_fifo_not_full : 1;
        u32 rx_fifo_not_empty : 1;
        u32 tx_finished : 1;
        u32 rx_parity_error : 1;
        u32 : 3;
        u32 ack_is_low : 1;
        u32 : 1;
        u32 irq : 1;
        u32 : 1;
        u32 timer : 21; 
    };
    u32 value;
} SIO_STAT;

struct input_device_base
{
    enum input_device_type type;
    void (*input_get_data)(struct input_device_base *device);
    u8 data[6]; // maximum number of input bytes generated by a device
};

struct sio_context
{
    u32 sequence_len;
    u32 sequence_index;
    enum sio_state state;
    SIO_STAT stat;
    u16 mode;
    u16 control;
    u16 baud_reload; // not sure if this needs a default value
    u8 rx_buffer;
    u8 mcd_checksum;
    enum mcd_command command;
    u32 mcd_addr;
    u8 flag;
    u8 prev;
    u8 mcd_buffer[128];

};

extern struct sio_context g_sio;

void sio_reset(void);
u16 sio_read(u32 offset);
void sio_write(u32 offset, u16 value);

#endif /* PAD_H */
